version: "3.2"
services:
  starwars_service:
    image: paulex10/starwars:latest
    container_name: starwarsservice
    ports:
      - "3000:3000"
    command: sh -c 'sleep 10s && knex migrate:latest'
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    depends_on:
      - db_service

  db_service:
    image: mysql:8.0.19
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data: {}
